#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// packages/core/scripts/gen-version.mjs
// Writes src/generated/version.ts as a plain string-literal constant taken from package.json's
// version field, so @dexpace/core never needs a runtime package.json read -- that would require
// node:fs / import.meta.url tricks unavailable on the browser/Workers half of core's runtime floor,
// and would leave those builds reporting the "unknown" placeholder NFR-15 forbids.
//
// Runs as the package's prebuild step. Its output is committed too, so a `bun test` run that has not
// built still sees a real (if stale) version rather than a placeholder.
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(packageRoot, 'src', 'generated', 'version.ts');

const {version} = JSON.parse(
  readFileSync(join(packageRoot, 'package.json'), 'utf8'),
);

if (typeof version !== 'string' || !/^[\w.+-]+$/.test(version)) {
  throw new Error(
    `gen-version: packages/core/package.json's "version" is missing or not a bare version string: ${String(version)}`,
  );
}

const contents = `// SPDX-License-Identifier: MIT
// packages/core/src/generated/version.ts
// Generated by scripts/gen-version.mjs from package.json -- do not edit by hand.

/** The published version of \`@dexpace/core\`, compiled in at build time (NFR-15). @internal */
export const SDK_VERSION = '${version}';
`;

mkdirSync(dirname(outputPath), {recursive: true});
writeFileSync(outputPath, contents);
console.log(`gen-version: wrote ${outputPath} (${version})`);
