// SPDX-License-Identifier: MIT
// scripts/knowledge.mjs
//
// Query surface over `docs/knowledge/`. The corpus is ~1.5k entries across two
// trees; without a filter, answering "what do we already know about RETRY-12"
// means reading a 20 KB file. This turns that into a query that returns the
// handful of entries that actually cite the requirement.
//
// Two trees, one query surface:
//   harvested/  generated by `knowledge-harvest`, never hand-edited. A `<sub>`
//               sha there digests the WHOLE source file, so a hand edit inside
//               an entry is invisible to the next harvest — it is regenerated
//               or duplicated. Hence: no hand edits, ever.
//   notes/      hand-written during implementation. Role `review`, a manual
//               `sha:` marker. What the implementation found, which outranks
//               what the documents say.
//
// `verify-knowledge-structure.mjs` is the gate that keeps the two apart. This
// file is not a gate — `--coverage` is a report you run by hand.
//
// Zero dependencies, plain Node ESM, same shape as the `verify-*.mjs` scripts.
import {createHash} from 'node:crypto';
import {readFileSync, readdirSync} from 'node:fs';
import {join, basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseArgs} from 'node:util';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const knowledgeDir = join(repoRoot, 'docs', 'knowledge');
const harvestedDir = join(knowledgeDir, 'harvested');
const notesDir = join(knowledgeDir, 'notes');
const appendixCPath = join(
  repoRoot,
  'docs',
  'product-spec',
  'appendix-c-consolidated-normative-requirement-index.md',
);

// `INDEX.md` is a generated topic table, `SOURCES.md` a provenance manifest and
// `README.md` the two-tree contract; none holds entries, and all would parse as
// noise.
const NON_TOPIC_FILES = new Set(['INDEX.md', 'SOURCES.md', 'README.md']);

// Appendix B is the conformance-test checklist. Its entries roll several
// requirement IDs into one "the suite verifies X, Y, Z" sentence, so they make
// an ID look cited while carrying none of its content. 256 of the 641 cited IDs
// resolve ONLY to a roll-up — a silent wrong answer unless it is called out.
const ROLLUP_SOURCE = 'appendix-b-conformance-test-checklist';

// Provenance roles the corpus uses, most common first. `review` is the notes
// tree's role and appears nowhere under `harvested/`.
const ROLES = ['spec', 'design', 'styleguide', 'review'];

// The two trees, and the value of an entry's `origin` field for each.
const ORIGINS = ['harvested', 'note'];
const TREES = [
  {origin: 'harvested', dir: harvestedDir, required: true},
  {origin: 'note', dir: notesDir, required: false},
];

// The six section names the parser recognises, in emission order. No file
// carries all six: `Superseded` exists only under `notes/`, where an override
// is recorded — `verify-knowledge-structure.mjs` rejects one under `harvested/`.
const SECTIONS = [
  'Rules',
  'Constraints',
  'Conclusions',
  'Reference',
  'Conflicts',
  'Superseded',
];

// ---------------------------------------------------------------------------
// Canonical requirement IDs
// ---------------------------------------------------------------------------

// A bare `\b[A-Z]{2,12}-\d+\b` is not a requirement-ID matcher: it also claims
// `UTF-8` (10 hits in the corpus), `SHA-256`, `ISO-8601` and `RFC-3986`. The
// only authority on what a requirement ID looks like is appendix C, so the
// prefix allowlist is derived from it at runtime and never hardcoded — a spec
// revision that adds a subsystem is picked up without editing this file.
const ID_TOKEN = /\b[A-Z][A-Z0-9]{1,11}-\d+\b/g;
const APPENDIX_C_ROW = /^\|\s*([A-Z][A-Z0-9]{1,11}-\d+)\s*\|/;

function loadCanonicalIds() {
  let text;
  try {
    text = readFileSync(appendixCPath, 'utf8');
  } catch (cause) {
    throw new Error(
      `cannot read the canonical requirement index at ${appendixCPath}; ` +
        'the requirement-ID allowlist is derived from it and there is no fallback',
      {cause},
    );
  }

  const ids = new Map();
  for (const line of text.split('\n')) {
    const match = APPENDIX_C_ROW.exec(line);
    if (!match) continue;
    const cells = line.split('|').map(cell => cell.trim());
    // `| ID | Level | Subsystem | Requirement |` — leading/trailing empties.
    ids.set(match[1], {
      id: match[1],
      level: cells[2] ?? '',
      subsystem: cells[3] ?? '',
    });
  }

  if (ids.size === 0) {
    throw new Error(
      `parsed zero requirement IDs out of ${appendixCPath}; its table format ` +
        'changed and the allowlist cannot be derived — refusing to fall back ' +
        'to a bare regex, which false-positives on UTF-8 and SHA-256',
    );
  }
  return ids;
}

function derivePrefixes(canonicalIds) {
  const prefixes = new Set();
  for (const id of canonicalIds.keys()) {
    prefixes.add(id.slice(0, id.lastIndexOf('-')));
  }
  return prefixes;
}

// Tokenize, then compare whole tokens. Never substring-match: `HTTP-7` and
// `HTTP-70` are different requirements and a substring test conflates them.
function extractIds(text, prefixes) {
  const found = [];
  for (const [token] of text.matchAll(ID_TOKEN)) {
    if (!prefixes.has(token.slice(0, token.lastIndexOf('-')))) continue;
    if (!found.includes(token)) found.push(token);
  }
  return found;
}

// ---------------------------------------------------------------------------
// Corpus parsing
// ---------------------------------------------------------------------------

const SECTION_HEADING = /^##\s+(.+?)\s*$/;
const BULLET_START = /^-\s+(.*)$/;
const SUB_LINE = /^\s+<sub>(.*)<\/sub>\s*$/;
const ROLE_AND_SOURCE = /^(\S+)\s+`(.+)`$/;
const BARE_SOURCE = /^`(.+)`$/;

// Two `<sub>` shapes are in the corpus:
//   role · `path:lines` · confidence · sha:xxxx        (the common one)
//   roleA `pathA` · roleB `pathB` · resolution-status  (Conflicts entries)
// so role and path are sometimes separate ` · ` fields and sometimes one. Walk
// the fields and classify each rather than reading them positionally.
function parseSub(inner) {
  const roles = [];
  const sources = [];
  let confidence = null;
  let sha = null;
  let pendingRole = null;

  for (const raw of inner.split(' · ')) {
    const field = raw.trim();

    const pair = ROLE_AND_SOURCE.exec(field);
    if (pair) {
      roles.push(pair[1]);
      sources.push(pair[2]);
      pendingRole = null;
      continue;
    }

    const bare = BARE_SOURCE.exec(field);
    if (bare) {
      roles.push(pendingRole ?? 'unknown');
      sources.push(bare[1]);
      pendingRole = null;
      continue;
    }

    if (field.startsWith('sha:')) {
      sha = field.slice('sha:'.length);
      continue;
    }

    // A lone word that is not a confidence level is the role of the source
    // field that follows it; anything else is the confidence / status.
    if (pendingRole !== null) confidence = pendingRole;
    pendingRole = /^\S+$/.test(field) ? field : null;
    if (pendingRole === null) confidence = field;
  }
  if (pendingRole !== null) confidence = pendingRole;

  return {
    role: roles[0] ?? null,
    roles,
    source: sources[0] ?? null,
    sources,
    confidence,
    sha,
  };
}

// A citable name for one entry, stable across a re-order and a re-harvest.
// The line number is not that name: an entry moves whenever a neighbour is
// added. The `<sub>` sha is not either — it digests the whole source file, so
// every entry harvested from one file shares it. The digest of the entry's own
// text changes when, and only when, the rule changes, which is what a note
// naming a broken rule wants: a changed rule needs a fresh check.
function entryKey(topic, text) {
  const hash = createHash('sha256').update(text.trimEnd()).digest('hex');
  return `${topic}/${hash.slice(0, 8)}`;
}

// A topic file authored on Windows, or saved with a BOM, is the one input that
// fails silently rather than loudly: `\r` defeats BULLET_START's `$` and a BOM
// defeats SECTION_HEADING, so the file parses to zero entries or to entries
// with no section, and every downstream gate then reports OK over a hole. The
// repo has no `.gitattributes`, so `core.autocrlf=true` is one contributor
// away. Normalize both at the door.
function readTopicFile(path) {
  let text;
  try {
    text = readFileSync(path, 'utf8');
  } catch (cause) {
    throw new Error(`cannot read the topic file ${path}`, {cause});
  }
  return text.replace(/^\uFEFF/, '').split(/\r?\n/);
}

// One bullet carrying two `<sub>` lines is malformed, but overwriting the first
// with the second drops its sources — and a source is what the structural gate
// checks, so the malformed half would escape the check. Accumulate instead, and
// let the gate see everything the entry cites.
function mergeSub(entry, parsed, subLine) {
  if (entry.subLine === null) {
    Object.assign(entry, parsed, {subLine});
    return;
  }
  entry.roles.push(...parsed.roles);
  entry.sources.push(...parsed.sources);
  entry.subLine += ` ${subLine}`;
}

function parseFile(path, prefixes, origin = 'harvested') {
  const entries = [];
  const lines = readTopicFile(path);
  const file = basename(path);
  const topic = file.replace(/\.md$/, '');
  let section = null;
  let current = null;

  const flush = () => {
    if (!current) return;
    current.reqs = extractIds(current.text, prefixes);
    current.key = entryKey(topic, current.text);
    entries.push(current);
    current = null;
  };

  for (const [index, line] of lines.entries()) {
    const heading = SECTION_HEADING.exec(line);
    if (heading) {
      flush();
      section = heading[1];
      continue;
    }

    const sub = SUB_LINE.exec(line);
    if (sub && current) {
      mergeSub(current, parseSub(sub[1]), line.trim());
      continue;
    }

    const bullet = BULLET_START.exec(line);
    if (bullet) {
      flush();
      current = {
        file,
        topic,
        origin,
        key: null,
        overriddenBy: [],
        overrides: [],
        line: index + 1,
        section,
        text: bullet[1],
        role: null,
        roles: [],
        source: null,
        sources: [],
        confidence: null,
        sha: null,
        subLine: null,
      };
      continue;
    }

    // A continuation line: any non-`<sub>` line before the open bullet's
    // provenance line, blank lines included — a few Conflicts entries run to
    // several paragraphs, and dropping the tail silently loses the requirement
    // IDs it cites. An entry therefore ends only at its `<sub>`, at the next
    // bullet, at the next heading, or at end of file.
    if (current && !current.subLine && line.trim() !== '') {
      current.text += ` ${line.trim()}`;
    }
  }

  flush();
  return entries;
}

function loadCorpus(prefixes) {
  const entries = topicFiles().flatMap(({path, origin}) =>
    parseFile(path, prefixes, origin),
  );
  return linkOverrides(entries);
}

// A note names the harvested rule it overrides by that rule's key. Resolve those
// references once, at load, and hang the answer on both ends.
//
// Without this the override is prose inside one note and nothing else: a query
// that lands on the harvested entry — by `--section reference`, by a bare word,
// by anything that does not also return the note — hands back a rule the
// implementation has already overruled, with no sign that it did. The corpus's
// highest-stakes entry is exactly that case: the pagination snippet whose note
// records that following it "would have shipped a MUST violation the checklist
// could not catch".
//
// `overriddenBy` is also how a stale reference becomes visible. A key digests
// entry text, so a re-harvest that rewords a rule leaves the citing note
// pointing at nothing; `danglingKeys` is that list, and `--key` reports it.
function linkOverrides(entries) {
  const byKey = new Map(entries.map(entry => [entry.key, entry]));
  for (const note of entries) {
    if (note.origin !== 'note') continue;
    for (const [, cited] of note.text.matchAll(CITED_KEY)) {
      const target = byKey.get(cited);
      if (target === undefined || target === note) continue;
      target.overriddenBy.push(entryLocation(note));
      note.overrides.push(cited);
    }
  }
  return entries;
}

// A key inside an entry's prose, backticked: `pagination/81881061`.
const CITED_KEY = /`([a-z0-9-]+\/[0-9a-f]{8})`/g;

function danglingKeys(entries) {
  const known = new Set(entries.map(entry => entry.key));
  const dangling = [];
  for (const note of entries) {
    if (note.origin !== 'note') continue;
    for (const [, cited] of note.text.matchAll(CITED_KEY)) {
      if (!known.has(cited)) dangling.push({note: entryLocation(note), cited});
    }
  }
  return dangling;
}

// Every topic file in both trees, harvested first, as records rather than bare
// names: a caller needs the tree an entry came from, and `pagination.md` exists
// in both.
function topicFiles() {
  return TREES.flatMap(({origin, dir, required}) =>
    readTree(dir, required).map(name => ({
      file: name,
      topic: name.replace(/\.md$/, ''),
      path: join(dir, name),
      origin,
    })),
  );
}

function readTree(dir, required) {
  let names;
  try {
    names = readdirSync(dir);
  } catch (cause) {
    if (required) {
      throw new Error(
        `cannot read the harvested corpus at ${dir}; docs/knowledge/ is two ` +
          'trees (harvested/ and notes/) and the harvested one is not optional',
        {cause},
      );
    }
    // The notes tree holds a file only where a note exists. None yet is a
    // legitimate state, not a broken checkout.
    return [];
  }
  return names
    .filter(name => name.endsWith('.md') && !NON_TOPIC_FILES.has(name))
    .sort();
}

// True when every source this entry cites is the conformance checklist, i.e.
// the entry names requirement IDs without saying anything about them.
function isRollup(entry) {
  return (
    entry.sources.length > 0 &&
    entry.sources.every(source => source.includes(ROLLUP_SOURCE))
  );
}

// Styleguide `<sub>` paths carry a numbered chapter file
// (`.../typescript/06-classes-and-data-modeling.md:168-183`), so "styleguide
// 6.7" is answerable by matching the chapter number — no hardcoded chapter →
// topic table that could drift from the styleguide itself.
// Only styleguide-role sources count: `docs/product-spec/04-…md` is a numbered
// chapter too, and conflating the two would answer "styleguide 4" with spec
// chapter 4. `roles[i]` pairs with `sources[i]`.
const STYLEGUIDE_CHAPTER = /\/(\d{2})-[^/]*\.md(?::|$)/;

function chaptersOf(entry) {
  const chapters = [];
  entry.sources.forEach((source, index) => {
    if (entry.roles[index] !== 'styleguide') return;
    const match = STYLEGUIDE_CHAPTER.exec(source);
    if (match) chapters.push(String(Number(match[1])));
  });
  return chapters;
}

// ---------------------------------------------------------------------------
// Filtering
// ---------------------------------------------------------------------------

// `--req A,B --req C` and `--req A --req B` mean the same thing: values inside
// one filter OR.
//
// An empty value is dropped, and a filter whose values were ALL empty throws.
// `--topic ''` and the one-character typo `--topic 'a,b,'` would otherwise match
// every file — `''` is a substring of everything and a regex that matches
// everything — so a trailing comma in the skill's own comma-separated audit form
// silently turns a 55-entry query into the whole corpus, which is the one thing
// this tool exists to prevent.
function splitValues(values, flag) {
  const supplied = (values ?? []).flatMap(value => value.split(','));
  const kept = supplied.filter(value => value.trim() !== '');
  if (supplied.length > 0 && kept.length === 0) {
    throw new Error(
      `${flag} was given only empty values; an empty value matches every ` +
        'entry, so this would print the whole corpus. Drop the flag, or a ' +
        'stray comma.',
    );
  }
  return kept;
}

function warnUncanonicalIds(reqs, canonicalIds) {
  for (const id of reqs) {
    if (canonicalIds.has(id)) continue;
    process.stderr.write(
      `warning: ${id} is not in appendix C — it is not a canonical ` +
        'requirement ID, so no entry can legitimately cite it\n',
    );
  }
}

function parseRoles(options) {
  return splitValues(options.role, '--role').map(value => {
    if (!ROLES.includes(value)) {
      throw new Error(
        `unknown role '${value}'; the roles are ${ROLES.join(', ')}`,
      );
    }
    return value;
  });
}

function parseOrigins(options) {
  return splitValues(options.origin, '--origin').map(value => {
    if (!ORIGINS.includes(value)) {
      throw new Error(
        `unknown origin '${value}'; the origins are ${ORIGINS.join(', ')} — ` +
          'harvested/ is what the documents say, notes/ what the ' +
          'implementation found',
      );
    }
    return value;
  });
}

// An ID family, for the audit query: `--prefix HTTP` is every HTTP-N entry,
// which `--req` cannot express without listing all 92 of them. Validated
// against appendix C for the same reason `--req` warns — `--prefix UTF` would
// otherwise be a silent empty result rather than a typo.
function parseIdPrefixes(options, known) {
  return splitValues(options.prefix, '--prefix').map(value => {
    const prefix = value.trim().toUpperCase();
    if (!known.has(prefix)) {
      throw new Error(
        `'${prefix}' is not a requirement-ID prefix in appendix C, so no ` +
          'entry can legitimately cite one. The prefixes are ' +
          `${[...known].sort().join(' ')}`,
      );
    }
    return prefix;
  });
}

// A key is `<topic>/<8 hex>`. Not validated against the corpus here: a key that
// resolves to nothing is exactly what a reader needs told — the note citing it
// is describing a rule whose text has changed — so it flows through to
// renderNoMatches, which says so.
const ENTRY_KEY = /^[a-z0-9-]+\/[0-9a-f]{8}$/;

function parseKeys(options) {
  return splitValues(options.key, '--key').map(value => {
    const key = value.trim();
    if (!ENTRY_KEY.test(key)) {
      throw new Error(
        `'${key}' is not an entry key; a key is <topic>/<8 hex>, as printed ` +
          'after the section name on every result',
      );
    }
    return key;
  });
}

// "styleguide 6.7" — the chapter is queryable, the sub-section number is not,
// so take the chapter and say plainly that the rest was dropped.
function parseChapters(options) {
  return splitValues(options.chapter, '--chapter').map(value => {
    const match = /^(\d{1,2})(?:\.(\d+))?$/.exec(value.trim());
    if (!match) {
      throw new Error(
        `unknown chapter '${value}'; expected a styleguide chapter like 6 or 6.7`,
      );
    }
    if (match[2] !== undefined) {
      process.stderr.write(
        'note: entries record a chapter file and line range, not section ' +
          `numbers — querying chapter ${match[1]}, ignoring .${match[2]}. ` +
          'Narrow with bare words.\n',
      );
    }
    return String(Number(match[1]));
  });
}

function parseSections(options) {
  return splitValues(options.section, '--section').map(value => {
    const resolved = SECTIONS.find(
      name => name.toLowerCase() === value.toLowerCase(),
    );
    if (!resolved) {
      throw new Error(
        `unknown section '${value}'; the six sections are ${SECTIONS.join(', ')}`,
      );
    }
    return resolved;
  });
}

// An empty pattern matches every entry, exactly as an empty `--topic` does, so
// it gets the same refusal rather than printing the corpus.
function parsePatterns(options, positionals) {
  const sources = [...(options.grep ?? []), ...positionals];
  if (sources.length > 0 && sources.every(value => value.trim() === '')) {
    throw new Error(
      '--grep was given only empty values; an empty pattern matches every ' +
        'entry, so this would print the whole corpus.',
    );
  }
  const patterns = [];
  for (const source of options.grep ?? []) {
    if (source.trim() !== '') patterns.push(new RegExp(source, 'i'));
  }
  for (const word of positionals) {
    if (word.trim() !== '') patterns.push(new RegExp(escapeRegExp(word), 'i'));
  }
  return patterns;
}

function buildFilters(options, positionals, canonicalIds) {
  const reqs = splitValues(options.req, '--req');
  warnUncanonicalIds(reqs, canonicalIds);

  return {
    reqs,
    topics: splitValues(options.topic, '--topic'),
    keys: parseKeys(options),
    origins: parseOrigins(options),
    prefixes: parseIdPrefixes(options, derivePrefixes(canonicalIds)),
    roles: parseRoles(options),
    chapters: parseChapters(options),
    sections: parseSections(options),
    patterns: parsePatterns(options, positionals),
  };
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Every supplied filter must hold — they AND, never OR. Within one filter,
// multiple values OR (`--req A --req B` is "cites A or B").
function matches(entry, filters) {
  const {
    reqs,
    topics,
    keys,
    origins,
    prefixes,
    roles,
    chapters,
    sections,
    patterns,
  } = filters;
  if (keys.length > 0 && !keys.includes(entry.key)) return false;
  if (reqs.length > 0 && !reqs.some(id => entry.reqs.includes(id)))
    return false;
  if (
    prefixes.length > 0 &&
    !entry.reqs.some(id => prefixes.includes(splitId(id)[0]))
  ) {
    return false;
  }
  if (topics.length > 0 && !topics.some(t => entry.file.includes(t))) {
    return false;
  }
  if (origins.length > 0 && !origins.includes(entry.origin)) return false;
  if (sections.length > 0 && !sections.includes(entry.section)) return false;
  if (roles.length > 0 && !roles.some(r => entry.roles.includes(r))) {
    return false;
  }
  if (chapters.length > 0) {
    const entryChapters = chaptersOf(entry);
    if (!chapters.some(c => entryChapters.includes(c))) return false;
  }
  if (!patterns.every(pattern => pattern.test(entry.text))) return false;
  return true;
}

function isEmptyFilter(filters) {
  return (
    filters.reqs.length === 0 &&
    filters.keys.length === 0 &&
    filters.prefixes.length === 0 &&
    filters.origins.length === 0 &&
    filters.topics.length === 0 &&
    filters.roles.length === 0 &&
    filters.chapters.length === 0 &&
    filters.sections.length === 0 &&
    filters.patterns.length === 0
  );
}

// ---------------------------------------------------------------------------
// Reports
// ---------------------------------------------------------------------------

function citationIndex(entries) {
  const index = new Map();
  for (const entry of entries) {
    for (const id of entry.reqs) {
      if (!index.has(id)) index.set(id, []);
      index.get(id).push(entry);
    }
  }
  return index;
}

function compareIds(a, b) {
  const [prefixA, numberA] = splitId(a);
  const [prefixB, numberB] = splitId(b);
  return prefixA === prefixB
    ? numberA - numberB
    : prefixA.localeCompare(prefixB);
}

function splitId(id) {
  const cut = id.lastIndexOf('-');
  return [id.slice(0, cut), Number(id.slice(cut + 1))];
}

function renderListReqs(index) {
  const out = [];
  for (const id of [...index.keys()].sort(compareIds)) {
    const locations = index
      .get(id)
      .map(entry => entryLocation(entry))
      .join(' ');
    out.push(`${id}\t${locations}`);
  }
  out.push('');
  out.push(`${index.size} requirement IDs cited across the corpus`);
  return out.join('\n');
}

function renderListTopics(entries) {
  const stats = new Map();
  for (const entry of entries) {
    const name = entry.topic;
    if (!stats.has(name)) {
      stats.set(name, {entries: 0, notes: 0, ids: new Set()});
    }
    const row = stats.get(name);
    if (entry.origin === 'note') row.notes += 1;
    else row.entries += 1;
    entry.reqs.forEach(id => row.ids.add(id));
  }
  const out = ['topic\tentries\tdistinct IDs\tnotes'];
  for (const [name, {entries: count, notes, ids}] of [...stats].sort()) {
    out.push(`${name}\t${count}\t${ids.size}\t${notes}`);
  }
  // Count only harvested topics as styleguide-derived: a note-only topic has no
  // requirement ID either, and calling it styleguide-derived is simply wrong.
  const idless = [...stats].filter(
    ([, v]) => v.ids.size === 0 && v.entries > 0,
  ).length;
  const noted = [...stats].filter(([, v]) => v.notes > 0).length;
  const harvested = [...stats].filter(([, v]) => v.entries > 0).length;
  out.push('');
  out.push(
    `${stats.size} topics, ${harvested} of them harvested. ${idless} ` +
      'harvested topics carry no requirement ID at all — those are ' +
      'styleguide-derived and are only reachable topic-first. ' +
      `${noted} topics carry a hand-written note (\`--origin note\`), which ` +
      'states what the implementation found and overrides the harvested entry.',
  );
  return out.join('\n');
}

function renderCoverage(canonicalIds, index) {
  const uncovered = [...canonicalIds.keys()]
    .filter(id => !index.has(id))
    .sort(compareIds);

  const byPrefix = new Map();
  let rollupOnlyTotal = 0;
  for (const id of canonicalIds.keys()) {
    const [prefix] = splitId(id);
    if (!byPrefix.has(prefix)) {
      byPrefix.set(prefix, {total: 0, missing: [], rollupOnly: []});
    }
    const row = byPrefix.get(prefix);
    row.total += 1;
    const hits = index.get(id);
    if (!hits) {
      row.missing.push(id);
    } else if (hits.every(isRollup)) {
      // Cited, but only by a conformance-checklist sentence that names it.
      row.rollupOnly.push(id);
      rollupOnlyTotal += 1;
    }
  }

  const out = ['requirement-ID coverage of docs/knowledge/', ''];
  out.push('prefix\tsubstantive\troll-up only\tuncited\ttotal\tuncited IDs');
  for (const prefix of [...byPrefix.keys()].sort()) {
    const {total, missing, rollupOnly} = byPrefix.get(prefix);
    const substantive = total - missing.length - rollupOnly.length;
    out.push(
      `${prefix}\t${substantive}\t${rollupOnly.length}\t${missing.length}\t` +
        `${total}\t${missing.length === 0 ? '-' : missing.join(' ')}`,
    );
  }
  const substantiveTotal =
    canonicalIds.size - uncovered.length - rollupOnlyTotal;
  out.push('');
  out.push(
    `${substantiveTotal}/${canonicalIds.size} canonical IDs have a substantive ` +
      `entry. ${rollupOnlyTotal} more are named only by an appendix-B ` +
      `conformance roll-up (cited, but no content). ${uncovered.length} are ` +
      'cited nowhere.',
  );
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

// `pagination.md` exists in both trees, so a bare basename is ambiguous. A
// harvested entry prints as `pagination.md:134`, a note as
// `notes/pagination.md:5`.
function entryLocation(entry) {
  const prefix = entry.origin === 'note' ? 'notes/' : '';
  return `${prefix}${entry.file}:${entry.line}`;
}

function plural(count, noun) {
  return `${count} ${noun}${count === 1 ? '' : 's'}`;
}

// The tags an entry can carry, in the order that matters to a reader: an
// override first, because it changes whether the entry is still true.
function tagsOf(entry) {
  const tags = (entry.overriddenBy ?? []).map(at => ` [overridden by ${at}]`);
  if (isRollup(entry)) tags.push(' [appendix-B roll-up]');
  return tags.join('');
}

function renderEntries(results, brief, filters) {
  const out = [];
  for (const entry of results) {
    const key = entry.key ? ` ${entry.key}` : '';
    out.push(
      `${entryLocation(entry)} (${entry.section})${key}${tagsOf(entry)}`,
    );
    out.push(`- ${entry.text}`);
    if (!brief && entry.subLine) out.push(`  ${entry.subLine}`);
    out.push('');
  }
  const files = new Set(
    results.map(entry => entryLocation(entry).split(':')[0]),
  );
  const notes = results.filter(entry => entry.origin === 'note').length;
  out.push(
    `${plural(results.length, 'entry').replace('entrys', 'entries')} across ` +
      `${plural(files.size, 'topic file')}` +
      (notes > 0
        ? `, ${notes} of them notes — a note states what the implementation ` +
          'found and overrides the harvested entry where it names one'
        : ''),
  );

  // The silent wrong answer this tool can give: a `--req` that "hits" but whose
  // every hit merely names the ID in a conformance-checklist sentence. Exit 0
  // makes it look answered, so say so loudly instead.
  if (results.every(isRollup) && (filters?.reqs.length ?? 0) > 0) {
    out.push(
      '',
      'WARNING: every result is an appendix-B conformance roll-up — it names ' +
        `${filters.reqs.join(', ')} without stating the requirement. The corpus ` +
        'has no substantive entry. Read the canonical text in appendix C and ' +
        'the owning docs/product-spec/NN chapter instead.',
    );
  }
  return out.join('\n');
}

// A zero-result query must never look like "the corpus has nothing to say" when
// it is really a typo, the wrong topic name, or two filters that cannot both
// hold. Spend the tokens on saying which of those it was.
//
// The dimension a hint blames has to be the dimension that emptied the result.
// A per-filter hint that fires unconditionally states falsehoods: with
// `--prefix HTTP --req PAGE-11` it used to report "PAGE-11 is canonical but no
// entry cites it yet", which is wrong — three entries cite it, none of them an
// HTTP one. So each dimension is first tested alone, and only a dimension that
// matches nothing on its own gets to explain itself.
const DIMENSIONS = [
  'reqs',
  'keys',
  'prefixes',
  'origins',
  'topics',
  'roles',
  'sections',
  'chapters',
  'patterns',
];

function soloFilters(filters, dimension) {
  const solo = Object.fromEntries(DIMENSIONS.map(name => [name, []]));
  solo[dimension] = filters[dimension];
  return solo;
}

function renderNoMatches(filters, entries, index, canonicalIds) {
  const out = ['no matching entries.'];
  const used = DIMENSIONS.filter(name => filters[name].length > 0);
  const barren = used.filter(
    name => !entries.some(entry => matches(entry, soloFilters(filters, name))),
  );

  if (barren.length === 0) {
    const alone = used
      .map(
        name =>
          `${name} ${entries.filter(entry => matches(entry, soloFilters(filters, name))).length}`,
      )
      .join(', ');
    out.push(
      '  every filter matches something on its own; no entry satisfies all ' +
        `of them at once (matching alone: ${alone}). Filters AND together — ` +
        'drop one.',
    );
    return out.join('\n');
  }

  for (const name of barren) {
    out.push(...HINTS[name](filters, entries, index, canonicalIds));
  }
  return out.join('\n');
}

function hintForReqs(filters, entries, index, canonicalIds) {
  const out = [];
  for (const id of filters.reqs) {
    const [prefix, number] = splitId(id);
    out.push(
      canonicalIds.has(id)
        ? `  ${id} is canonical but no entry cites it yet.`
        : `  ${id} is not a canonical requirement ID (not in appendix C).`,
    );
    // Never offer the queried ID back as its own nearest neighbour.
    const nearest = [...index.keys()]
      .filter(other => other !== id && splitId(other)[0] === prefix)
      .sort((a, b) => {
        const distance =
          Math.abs(splitId(a)[1] - number) - Math.abs(splitId(b)[1] - number);
        return distance === 0 ? compareIds(a, b) : distance;
      })
      .slice(0, 5);
    out.push(
      nearest.length > 0
        ? `  nearest cited ${prefix} IDs: ${nearest.join(' ')}`
        : `  no ${prefix} ID is cited anywhere. cited prefixes: ${[
            ...new Set([...index.keys()].map(other => splitId(other)[0])),
          ]
            .sort()
            .join(' ')}`,
    );
    const topics = topicsForPrefix(entries, prefix);
    if (topics.length > 0) {
      out.push(`  topics carrying ${prefix} knowledge: ${topics.join(' ')}`);
    }
  }
  return out;
}

// A key that resolves to nothing is not a typo, it is news: the entry it named
// has been reworded, so whatever cites it — a note, an audit — is describing a
// rule that no longer exists in that form and needs a fresh check.
function hintForKeys(filters, entries) {
  return filters.keys.map(key => {
    const [topic] = key.split('/');
    const citedBy = entries
      .filter(entry => entry.text.includes(`\`${key}\``))
      .map(entry => entryLocation(entry));
    const known = entries.some(entry => entry.topic === topic);
    const where =
      citedBy.length > 0 ? ` It is cited by ${citedBy.join(' ')}` : '';
    return known
      ? `  no entry carries the key ${key}. A key digests the entry's text, ` +
          `so a reworded or re-harvested rule gets a new one.${where}` +
          (citedBy.length > 0 ? ', which needs updating.' : '')
      : `  no entry carries the key ${key}, and no topic '${topic}' exists.`;
  });
}

function hintForPrefixes(filters) {
  return filters.prefixes.map(prefix => `  no entry cites any ${prefix} ID.`);
}

function hintForOrigins(filters) {
  return filters.origins.map(origin =>
    origin === 'note'
      ? '  the notes tree carries only what an implementation found that ' +
        'overrides a harvested rule; it is meant to be small.'
      : '  no harvested entry matches. harvested/ is the whole corpus bar the ' +
        'notes, so this is a filter combination, not an empty tree.',
  );
}

function hintForTopics(filters, entries) {
  const known = [...new Set(entries.map(entry => entry.topic))].sort();
  return filters.topics.map(
    topic =>
      `  no topic file matches '${topic}'. available: ${known.join(' ')}`,
  );
}

function hintForRoles(filters) {
  return filters.roles.map(role =>
    role === 'review'
      ? "  no review-role entry matches. review is the notes tree's role; " +
        'under harvested/ it is a structural violation, so there are none.'
      : `  no entry carries the role ${role}.`,
  );
}

function hintForSections(filters) {
  return filters.sections.map(
    section =>
      `  the ${section} section holds no entry in either tree` +
      (section === 'Superseded'
        ? ' — it exists only under notes/, where an override is recorded.'
        : '.'),
  );
}

function hintForChapters(filters, entries) {
  const known = [...new Set(entries.flatMap(entry => chaptersOf(entry)))].sort(
    (a, b) => Number(a) - Number(b),
  );
  return filters.chapters.map(
    chapter =>
      `  no entry cites styleguide chapter ${chapter}. harvested chapters: ` +
      known.join(' '),
  );
}

function hintForPatterns() {
  return [
    '  text filters are applied to entry text only; try --grep with a ' +
      'looser pattern, or fewer bare words.',
  ];
}

const HINTS = {
  reqs: hintForReqs,
  keys: hintForKeys,
  prefixes: hintForPrefixes,
  origins: hintForOrigins,
  topics: hintForTopics,
  roles: hintForRoles,
  sections: hintForSections,
  chapters: hintForChapters,
  patterns: hintForPatterns,
};

function topicsForPrefix(entries, prefix) {
  const counts = new Map();
  for (const entry of entries) {
    for (const id of entry.reqs) {
      if (splitId(id)[0] !== prefix) continue;
      counts.set(entry.topic, (counts.get(entry.topic) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([topic]) => topic);
}

const USAGE = `Usage: bun run knowledge [options] [words...]

Query docs/knowledge/ — both harvested/ (what the documents say) and notes/
(what the implementation found; it overrides). Different filters AND together;
values within one filter OR.

  --req <ID>          entries citing that requirement ID (repeatable, comma-ok).
                      Comma form is the whole-task query: --req HTTP-13,HTTP-14
  --key <topic/hex>   the one entry with that key — how a note's citation is
                      resolved. An unknown key is reported, not an error: it
                      means the entry was reworded and the citation is stale.
  --prefix <name>     a whole ID family: --prefix HTTP. The audit-scale filter.
  --origin <names>    ${ORIGINS.join(' | ')}
  --topic <names>     topic files whose name contains any of these (substring)
  --section <names>   ${SECTIONS.map(s => s.toLowerCase()).join(' | ')}
  --role <names>      ${ROLES.join(' | ')}
  --chapter <n>       styleguide chapter, e.g. 6 (a "6.7" drops the .7)
  --grep <regex>      case-insensitive regex over entry text (repeatable)
  <words...>          bare words: case-insensitive substrings, all must match
  --brief             drop <sub> provenance lines (~30% less output)
  --json              machine-readable records
  --list-topics       every topic with entry, distinct-ID and note counts
  --list-reqs         requirement-ID -> location map (~6k tokens; prefer --coverage)
  --coverage          substantive vs roll-up-only vs uncited, per prefix
  --help

Every result carries a stable key, <topic>/<8 hex>, digested from the entry
text. Name a rule by that key in a note: it survives a re-order, and it changes
exactly when the rule's text does — including on a re-harvest that rewords it,
which is when the note needs revisiting. Resolve one with --key. A harvested
entry a note overrides prints [overridden by notes/...].

An unknown --role, --section, --chapter, --origin or --prefix exits 2: a typo
there is a silent empty result. An unknown --req only warns, because a
not-yet-canonical ID is a legitimate thing to ask about.

Exits 1 when a query matches nothing.

Examples:
  bun run knowledge --req HTTP-13,HTTP-14,HTTP-15   # one task's whole ID set
  bun run knowledge --origin note --brief           # start of a phase: what we found
  bun run knowledge --prefix HTTP --section rules   # an audit group, by ID family
  bun run knowledge --chapter 6 interface class     # "styleguide 6.7"
  bun run knowledge --topic pipeline --section rules --brief cursor fork
`;

function main(argv) {
  const {values, positionals} = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      req: {type: 'string', multiple: true},
      key: {type: 'string', multiple: true},
      prefix: {type: 'string', multiple: true},
      origin: {type: 'string', multiple: true},
      topic: {type: 'string', multiple: true},
      section: {type: 'string', multiple: true},
      role: {type: 'string', multiple: true},
      chapter: {type: 'string', multiple: true},
      grep: {type: 'string', multiple: true},
      brief: {type: 'boolean', default: false},
      json: {type: 'boolean', default: false},
      'list-topics': {type: 'boolean', default: false},
      'list-reqs': {type: 'boolean', default: false},
      coverage: {type: 'boolean', default: false},
      help: {type: 'boolean', default: false},
    },
  });

  if (values.help) {
    process.stdout.write(USAGE);
    return 0;
  }

  const canonicalIds = loadCanonicalIds();
  const entries = loadCorpus(derivePrefixes(canonicalIds));
  const index = citationIndex(entries);

  if (values['list-topics']) {
    process.stdout.write(`${renderListTopics(entries)}\n`);
    return 0;
  }
  if (values['list-reqs']) {
    process.stdout.write(`${renderListReqs(index)}\n`);
    return 0;
  }
  if (values.coverage) {
    process.stdout.write(`${renderCoverage(canonicalIds, index)}\n`);
    return 0;
  }

  const filters = buildFilters(values, positionals, canonicalIds);
  if (isEmptyFilter(filters)) {
    process.stdout.write(USAGE);
    return 0;
  }

  const results = entries.filter(entry => matches(entry, filters));

  if (values.json) {
    const annotated = results.map(entry => ({
      ...entry,
      rollup: isRollup(entry),
    }));
    process.stdout.write(`${JSON.stringify(annotated, null, 2)}\n`);
    return results.length === 0 ? 1 : 0;
  }

  if (results.length === 0) {
    process.stdout.write(
      `${renderNoMatches(filters, entries, index, canonicalIds)}\n`,
    );
    return 1;
  }

  process.stdout.write(`${renderEntries(results, values.brief, filters)}\n`);
  return 0;
}

export {
  ROLES,
  SECTIONS,
  loadCanonicalIds,
  derivePrefixes,
  extractIds,
  entryKey,
  parseSub,
  parseFile,
  loadCorpus,
  citationIndex,
  buildFilters,
  matches,
  renderCoverage,
  renderEntries,
  renderListTopics,
  renderNoMatches,
  isRollup,
  chaptersOf,
  danglingKeys,
  entryLocation,
  topicFiles,
  compareIds,
  main,
};

// Only run the CLI when invoked directly, so the test file can import the
// parsing helpers without the process exiting underneath it.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 2;
  }
}
